### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by larsenwork** [fontforge/YosemiForge#3]
**To-do**
- [ ] Fix font sizes (maybe even metrics)?
- [ ] Correct folder + file icon
- [ ] Fix the buttons

**Comment by sharky127** [comment]
Hey, what's on the agenda?

**Comment by larsenwork** [comment]
Great. I can see you're new to git. Are you up to a short + non technical introduction? You will be using git a lot in the future so might as well start somewhere :wink:

**Comment by sharky127** [comment]
sure!

**Comment by larsenwork** [comment]
Great get http://www.sourcetreeapp.com

**Comment by larsenwork** [comment]
Once installed then file -> new/clone and paste this url https://github.com/andreaslarsen/YosemiForge

**Comment by larsenwork** [comment]
I'm closing this issue (since all the fontforge team members get notifications when we talk here). 
What I've done is I've forked
- github.com/fontforge/YosemiForge 

to
- github.com/andreaslarsen/YosemiForge/

where I've added you as collaborator (meaning you can make changes to the files)
You can create a new issue [here](https://github.com/andreaslarsen/YosemiForge/issues) when you've successfully downloaded the sourcetreeapp and maybe even succeeded with creating a local clone using sourcetreeapp

**Comment by adrientetar** [comment]
> (since all the fontforge team members get notifications when we talk here)

This will only happen for people who subscribe to the repo.

**Comment by larsenwork** [comment]
Ah, I didn't know that - I haven't been part of a bigger team on GitHub before and started getting many notifications after joining FontForge.
It's a good thing we moved it to a fork anyway since @sharky127 can't commit directly to FontForge :)
